### ISSUE TITLE
increase resolution wrt operational intensity

### ISSUE THREAD

**Issue by jevbelikov** [CAMP-benchmark/CAMP#2]
As a user I would like to be able to zoom onto the 0.0 < operational intensity <= 1.0 region. This may require changing the innermost caluclation from Triad to something else.

**Comment by jevbelikov** [comment]
perhaps we could switch to something closer  to STREAM ADD, but somewhat artificial in storing results of adding in three arrays? this would give operational intensity of ca 0.021 (N FLOPS/ N*48 bytes for 8-byte doubles);

```
tmp = a[i] + b[i]
a[i] = tmp
b[i] = tmp
c[i] = tmp
```

**Comment by pvvq** [comment]
That's something we can do. By the way, do you mean the OI of 0.021 i.e. 1/48? I find an [additional manual of roofline in the ERT repo](https://bitbucket.org/berkeleylab/cs-roofline-toolkit/src/master/Docs/Background/Sam_Williams_BLW_Roofline_Chapter.pdf) (ch9.1.4) and it provides several example of estimate operational intensity (arithmetic intensity).

Additionally, in ch 9.3.4 of this doc, I also find "Generally, small strides (less than the cache line size) should be interpreted as a decrease in arithmetic intensity, where large strides can represent a lack of spatial locality and memory-level parallelism.". Maybe that's an alternative way towards lower intensity, and that's why we observed obvious underpopulation phenomenon in our past stride result.

**Comment by jevbelikov** [comment]
yes 0.021, I will edit above comment too.

**Comment by pvvq** [comment]
[There are different ways to count Bytes](https://www.cs.virginia.edu/stream/ref.html#counting). STREAM benchmark counts the requested number of Bytes, but [some comment argues that the `hardware` Bytes are actually counted](https://blogs.fau.de/hager/archives/8263) since a write generates a load and a store.

We first empirically validate the `hardware` bytes by comparing the runtime and bandwidth of two kernels, STREAM ADD `c[i] = a[i] + b[i]` and our synthetic kernel which is named `TMP` temporarily.

```
tmp = a[i] + b[i]
a[i] = tmp
b[i] = tmp
c[i] = tmp
```

To ensure a fair comparison, all kernels are first compiled with loop unroll factor 1 and vectorisation is enabled. Vectorisation width is 4 in all cases. Array size is 2048000000 and we run 5 times. Results are as follows:

```
STREAM ADD:
Time(s) {min, avg, max}: {0.2048, 0.2052, 0.2054}
Traffic is 4.000000 Bytes per iteration
Bandwidth(B/s) {max, avg, min} is {320073576197.3740, 319439529669.1251, 318993791299.3224}
------------
TMP:
Time {min, avg, max}: {0.3107, 0.3111, 0.3113}
Traffic is 6.000000 Bytes per iteration
Bandwidth {max, avg, min} is {316412536895.5083, 316031290966.0750, 315796501807.1583}
```

We notice `TMP` kernel costs a longer runtime than `ADD`. If we blame this on the larger amount of Bytes moved per iteration, we get the roughly same bandwidth, which makes sense as these two kernels are both memory-intensive.

We then use HWPC to measure the number of FLOP and Byte but the result is unsatisfying. We force the loop unroll factor to 4 due to #4. 

```
STREAM ADD:
  USER / main.LOOP@li.78
------------------------------------------------------------------------------
  Time%                                                49.1% 
  Time                                              1.033882 secs
  Imb. Time                                         0.026446 secs
  Imb. Time%                                            2.6% 
  Calls                           4.836 /sec             5.0 calls
  PAPI_L2_DCM                     0.024G/sec  25,112,344.000 misses
  PAPI_FP_OPS                     0.033G/sec  33,909,204.000 ops
  CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS:
    LS_RD_BLK_C                   0.024G/sec      25,112,344 req
  L2_PREFETCH_HIT_L2              0.005G/sec       5,353,620 hits
  L2_PREFETCH_HIT_L3              0.043M/sec          44,602 hits
  REQUESTS_TO_L2_GROUP1:L2_HW_PF  0.214G/sec     221,159,324 ops
  REQUESTS_TO_L2_GROUP1:RD_BLK_X  0.060G/sec      62,114,108 ops
  HW FP Ops / User time           0.033G/sec      33,909,204 ops
  MFLOPS (aggregate)              32.80M/sec                 
  Cache Lines PF from OffCore     0.209G/sec     215,805,704 lines
  Cache Lines PF from Memory      0.209G/sec     215,761,102 lines
  Cache Lines Requested from 
    Memory                        0.024G/sec      25,107,154 lines
  Write Memory Traffic GBytes     3.751G/sec            3.88 GB
  Read Memory Traffic GBytes     14.910G/sec           15.42 GB
  Memory traffic GBytes          18.662G/sec           19.29 GB
  Memory Traffic / Nominal Peak                         9.1% 
  Average Time per Call                             0.206776 secs
  CrayPat Overhead : Time          0.0%     

TMP:
  USER / main.LOOP@li.78
------------------------------------------------------------------------------
  Time%                                                46.0% 
  Time                                              1.543131 secs
  Imb. Time                                         0.009314 secs
  Imb. Time%                                            0.6% 
  Calls                           3.240 /sec             5.0 calls
  PAPI_L2_DCM                     0.004G/sec   5,738,255.000 misses
  PAPI_FP_OPS                     0.020G/sec  30,432,769.000 ops
  CORE_TO_L2_CACHEABLE_REQUEST_ACCESS_STATUS:
    LS_RD_BLK_C                   0.004G/sec       5,738,255 req
  L2_PREFETCH_HIT_L2              0.873M/sec       1,347,881 hits
  L2_PREFETCH_HIT_L3              0.094M/sec         144,559 hits
  REQUESTS_TO_L2_GROUP1:L2_HW_PF  0.153G/sec     236,390,296 ops
  REQUESTS_TO_L2_GROUP1:RD_BLK_X  0.007G/sec      10,215,839 ops
  HW FP Ops / User time           0.020G/sec      30,432,769 ops
  MFLOPS (aggregate)              19.72M/sec                 
  Cache Lines PF from OffCore     0.152G/sec     235,042,415 lines
  Cache Lines PF from Memory      0.152G/sec     234,897,856 lines
  Cache Lines Requested from 
    Memory                        0.004G/sec       5,734,726 lines
  Write Memory Traffic GBytes     0.421G/sec            0.65 GB
  Read Memory Traffic GBytes      9.980G/sec           15.40 GB
  Memory traffic GBytes          10.401G/sec           16.05 GB
  Memory Traffic / Nominal Peak                         5.1% 
  Average Time per Call                             0.308626 secs
  CrayPat Overhead : Time          0.0% 
```

We notice the `Read Memory Traffic` barely increase and we lost track of `Write Memory Traffic` when we switch from `STREAM ADD` to `TMP`. The values of FLOP and memory both deviate from theoretical values. We expect FLOP to be same as array size `2,048,000,000/4(vectorisation) = 512,000,000` and traffic to be `2G(size) * 4or6(Bytes/iter) * 5(trials) = 40or60 GB`. One confirmation HWPC provides us is the value of FLOP is similar.

Additionally, we also test two variations of `TMP` kernel:

```
NOTMP:
c[i] = a[i] + b[i];
a[i] = c[i];
b[i] = c[i];

MORE:
tmp = a[i] + b[i];
a[i] = tmp;
b[i] = tmp;
c[i] = tmp;
d[i] = tmp;
```

`NOTMP` aims to discover the impact of the temporal variables. We confirm these two kernels behave the same except FLOP increase to `33,572,087` (9.4%).

We bring `MORE` to see if we can introduce more traffic by adding additional writes and the answer is true. Memory traffic increases to `21.69GB` (35%). The weird thing is FLOP drops to `23,206,978` (23%). We tried further introducing `e[i]` but the compiler refused to unroll which led to profiling failure.

The plain runtime of kernels can be found in `rt_kernel_plain_all.out` and profiling results in `rst_kernel_hwpc_[KERNEL]+pat.txt` in [unroll1](https://github.com/CAMP-benchmark/CAMP/tree/hwpc/hwpc/unroll1) and [unroll4](https://github.com/CAMP-benchmark/CAMP/tree/hwpc/hwpc/unroll4) folder.

**Comment by pvvq** [comment]
Bandwidth scaling of above kernels, `TMP` use fewer threads to achieve the best bandwidth than `STREAM ADD`.

![simple_kernel_bw_scaling](https://user-images.githubusercontent.com/57176977/221197671-60172b82-d322-4e8c-a052-999c96f67bc2.png)

**Comment by jevbelikov** [comment]
Having 0.021 is suffiecient, but we can consider whether we can get down to 0.01 in the future.
